---
# EC2NodeClass - 노드 구성 정의
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: KarpenterNodeRole-eks-product
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-product
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-product

---
# NodePool - 노드 프로비저닝 정책
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3.medium"]
      nodeClassRef:
        name: default
  
  # 노드 개수 제한: 1~5개
  disruption:
    consolidationPolicy: WhenUnderutilized
    consolidateAfter: 30s
    budgets:
    - nodes: "1-5"  # 최소 1개, 최대 5개 노드 유지
